export const LOADING = "LOADING";
export const ACCOUNT = "ACCOUNT";
export const DASHBOARD = "DASHBOARD";
export const RESET_PROJECT = "RESET_PROJECT";

// DASHBOARD
export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS";
export const GET_DASHBOARD_SUCCESS = "GET_DASHBOARD_SUCCESS";

export const GET_ACCOUNT_FAIL = "GET_ACCOUNT_FAIL";
export const GET_DASHBOARD_FAIL = "GET_DASHBOARD_FAIL";

export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";

// ORDER
export const GET_ORDER_LIST = "GET_ORDER_LIST";
export const CREATE_ORDER = "CREATE_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const DELETE_ORDER_IN = "DELETE_ORDER_IN";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";
export const GET_ORDER = "GET_ORDER";
export const CREATE_ORDERITEM = "CREATE_ORDERITEM";
export const CREATE_ORDERIMAGE = "CREATE_ORDERIMAGE";
export const GET_ORDERITEMS = "GET_ORDERITEMS";
export const GET_ORDERIMAGES = "GET_ORDERIMAGES";
export const GET_ORDERIMAGE_SUCCESS = "GET_ORDERIMAGE_SUCCESS";
export const GET_ORDERITEMS_SUCCESS = "GET_ORDERITEMS_SUCCESS";
export const CREATE_ORDER_PRICE = "CREATE_ORDER_PRICE";
export const DELETE_ORDER_ITEM = "DELETE_ORDER_ITEM";

//CUSTOMER
export const GET_CUSTOMER_LIST = "GET_CUSTOMER_LIST";
export const GET_CUSTOMER = "GET_ORDER";
export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const UPDATE_CUSTOEMR = "UPDATE_CUSTOMER";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_FAIL = "GET_CUSTOMER_FAIL";
export const GET_CUSTOMERLIST_SUCCESS = "GET_CUSTOMERLIST_SUCCESS";
export const GET_CUSTOMERLIST_FAIL = "GET_CUSTOMERLIST_FAIL";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const GET_MEMO = "GET_MEMO";
export const GET_MEMOS_SUCCESS = "GET_MEMOS_SUCCESS";

//Product
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";
export const QTY_PRODUCT = "QTY_PRODUCT";

//Category
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAIL = "CATEGORY_FAIL";

//Farm
export const GET_FARM_LIST = "GET_FARM_LIST";
export const CREATE_FARM = "CREATE_FARM";
export const UPDATE_FARM = "UPDATE_FARM";
export const DELETE_FARM = "DELETE_FARM";
export const FARM_SUCCESS = "FARM_SUCCESS";
export const FARM_FAIL = "FARM_FAIL";

//Logs
export const GET_LOG_LIST = "GET_LOG_LIST";
export const GET_RECENT_LOG_LIST = "GET_RECENT_LOG_LIST";
export const CREATE_LOG = "CREATE_LOG";
export const UPDATE_LOG = "UPDATE_LOG";
export const DELETE_LOG = "DELETE_LOG";
export const LOG_SUCCESS = "LOG_SUCCESS";
export const LOG_FAIL = "LOG_FAIL";
